### ISSUE TITLE
Bug where game crashes when a player fails to commit human words

### ISSUE THREAD

**Issue by snesguy** [fenceFoil/FindRealHumansNearYouGame#3]

**Comment by snesguy** [comment]
How about we pre-populate human words with canned words. And then when they are committed overwrite them.

**Comment by snesguy** [comment]
Can pre-populate the human words before switching the gamestate to writing pickups

**Comment by fenceFoil** [comment]
Fixed getting prospects erroring if any player or bot has no pickup line. Changed pickup line generation to generate dummy backup lines for players who have abandoned game if needed using any time left in writing pickups phase, even if we go overtime.

**Comment by fenceFoil** [comment]
Testing changes now...

**Comment by fenceFoil** [comment]
Chased down all the issues I could find here, the pickup line writing stage always transitions to swiping as expected now. Did what you suggested, and added a tag to PickupLine class for whether a line is a generated dummy line or not.
